# Generated by Django 2.2.7 on 2020-01-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Code', max_length=3, unique=True)),
                ('nationality', models.CharField(db_index=True, help_text='Nationality', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, unique=True, verbose_name='Degree')),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'guru',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Language')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Language Code')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'occupation',
                'ordering': ['occupation'],
            },
        ),
        migrations.CreateModel(
            name='MatrimonyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('rounds_chanting', models.PositiveIntegerField(default=0, help_text='How many rounds are you chanting?', verbose_name='Rounds')),
                ('s_status', models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter siksha status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Siksha Status')),
                ('dob', models.DateField(help_text='Enter birth date as YYYY-MM-DD', verbose_name='Birth Date')),
                ('tob', models.TimeField(help_text='Enter time HH:MM:SS in 24hr format', verbose_name='Birth Time')),
                ('birth_city', models.CharField(help_text='Enter birth village/town/city', max_length=200, verbose_name='City')),
                ('birth_state', models.CharField(max_length=200, verbose_name='State')),
                ('current_city', models.CharField(help_text='Enter current village/town/city', max_length=200, verbose_name='City')),
                ('current_state', models.CharField(max_length=200, verbose_name='State')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5)),
                ('complexion', models.CharField(blank=True, choices=[('I', 'Light, Pale White'), ('II', 'White, Fair'), ('III', 'Medium, White to light brown'), ('IV', 'Olive, moderate brown'), ('V', 'Brown, dark brown'), ('VI', 'Very dark brown to black')], help_text='Enter your complexion', max_length=3)),
                ('annual_income', models.PositiveIntegerField(help_text='Enter income in a year')),
                ('marital_status', models.CharField(choices=[('SGL', 'Single'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widow')], help_text='Single, Divorced etc.', max_length=3)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, verbose_name='Phone number')),
                ('expectations', models.TextField(max_length=300, null=True)),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthCountry', to='matrimony.Country', verbose_name='Country')),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCountry', to='matrimony.Country', verbose_name='Country')),
                ('degree', models.ForeignKey(help_text='H.S., Graduate etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Degree')),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Guru')),
                ('languages_known', models.ManyToManyField(help_text='Add the language you know', to='matrimony.Language')),
                ('occupation', models.ForeignKey(help_text='Surgeon, Computer Application Engineer, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Occupation')),
            ],
            options={
                'db_table': 'matrimony_profile',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matrimony.country',),
        ),
    ]
