# Generated by Django 2.2.7 on 2020-01-31 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
            ],
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='annual_income',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.User'),
        ),
    ]
