# Generated by Django 2.2.7 on 2020-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='female_response_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='male_response_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
