# Generated by Django 2.2.7 on 2020-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_auto_20200131_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='annual_income',
            field=models.PositiveIntegerField(),
        ),
    ]
