# Generated by Django 2.2.7 on 2020-04-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0002_auto_20200409_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Degree')),
            ],
            options={
                'db_table': 'qualifications',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='guru',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='monthly_income',
            new_name='annual_income',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='monthly_income_currency',
            new_name='annual_income_currency',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='occupation',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='s_status',
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guru',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='spiritual_status',
            field=models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter spiritual status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Siksha Status'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occupation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='marital_status',
            field=models.CharField(choices=[('UMR', 'Unmarried'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widowed')], help_text='Single, Divorced etc.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='guru',
            table='gurus',
        ),
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
        migrations.AlterModelTable(
            name='matrimonyprofile',
            table='matrimony_profiles',
        ),
        migrations.AlterModelTable(
            name='occupation',
            table='occupations',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='qualification',
            field=models.ForeignKey(help_text='H.S., Graduate etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Qualification'),
        ),
    ]
