# Generated by Django 2.2.7 on 2020-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_auto_20201018_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_visible_to_all_matches',
            field=models.BooleanField(blank=True, default=True, help_text='By default, your photos will be visible to all suggested matches. If you uncheck this option, your photos will only be visible to matches you have accepted.', null=True),
        ),
    ]
