# Generated by Django 2.2.7 on 2020-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_auto_20201018_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='is_tob_unknown',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Is birth time unknown?'),
        ),
    ]
