# Generated by Django 2.2.7 on 2020-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_auto_20200411_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAI', 'Fair'), ('VFA', 'Very fair'), ('WHT', 'Wheatish'), ('WHB', 'Wheatish brown'), ('DAR', 'Dark')], help_text='Enter your complexion', max_length=3, null=True),
        ),
    ]
