# Generated by Django 2.2.7 on 2020-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_auto_20200131_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_city',
            field=models.CharField(help_text='Enter birth village/town/city', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_state',
            field=models.CharField(max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('I', 'Light, Pale White'), ('II', 'White, Fair'), ('III', 'Medium, White to light brown'), ('IV', 'Olive, moderate brown'), ('V', 'Brown, dark brown'), ('VI', 'Very dark brown to black')], help_text='Enter your complexion', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_city',
            field=models.CharField(help_text='Enter current village/town/city', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_state',
            field=models.CharField(max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='dob',
            field=models.DateField(help_text='Enter birth date as YYYY-MM-DD', null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='marital_status',
            field=models.CharField(choices=[('UM', 'Unmarried'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widowed')], help_text='Single, Divorced etc.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='phone',
            field=models.CharField(max_length=17, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='tob',
            field=models.TimeField(help_text='Enter time HH:MM:SS in 24hr format', null=True, verbose_name='Birth Time'),
        ),
    ]
