# Generated by Django 2.2.7 on 2020-03-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_auto_20200318_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
