# Generated by Django 2.2.7 on 2020-12-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_auto_20201122_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('male', 'female')},
        ),
    ]
