# Generated by Django 2.2.7 on 2020-11-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_matrimonyprofile_registration_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('male', 'female')},
        ),
    ]
