# Generated by Django 2.2.7 on 2020-04-12 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_auto_20200412_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matrimony.matrimonyprofile',),
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matrimony.matrimonyprofile',),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
