# Generated by Django 2.2.7 on 2020-11-22 10:36

from django.db import migrations


def update_registration_date(apps, schema_editor):
    MatrimonyProfile = apps.get_model('matrimony', 'MatrimonyProfile')
    for profile in MatrimonyProfile.objects.all():
        profile.registration_date = profile.created_at
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_auto_20201119_0737'),
    ]

    operations = [
        migrations.RunPython(update_registration_date),
    ]
