# Generated by Django 2.2.7 on 2020-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0005_auto_20200412_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5, null=True),
        ),
    ]
