# Generated by Django 2.2.7 on 2020-03-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_matrimonyprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='annual_income',
            new_name='monthly_income',
        ),
    ]
