# Generated by Django 2.2.7 on 2020-12-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_auto_20201122_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='is_tob_unknown',
        ),
        migrations.AlterField(
            model_name='match',
            name='female',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='male_matches', to='matrimony.Female'),
        ),
        migrations.AlterField(
            model_name='match',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female_matches', to='matrimony.Male'),
        ),
    ]
