# Generated by Django 2.2.7 on 2020-12-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0006_auto_20201122_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrimonyprofile',
            options={'ordering': ['-registration_date']},
        ),
    ]
