# Generated by Django 2.2.7 on 2021-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0007_order_by_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='photos_visible_to_all_matches',
            field=models.BooleanField(blank=True, default=True, help_text='By default, your photos will be visible to all suggested matches. If you uncheck this option, your photos will only be visible to matches you have accepted.', null=True),
        ),
    ]
