# Generated by Django 2.2.7 on 2021-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0008_photos_visible_to_all_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='is_tob_unknown',
        ),
        migrations.AddField(
            model_name='match',
            name='female_photos_visibility',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='male_photos_visibility',
            field=models.NullBooleanField(),
        ),
    ]
