# Generated by Django 2.2.7 on 2020-05-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0009_auto_20200502_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=2000)),
                ('to', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SNT', 'Sent'), ('FLD', 'Failed')], default='NEW', max_length=3)),
                ('category', models.CharField(choices=[('DMD', 'Daily matches digest'), ('MAN', 'Manual')], default='MAN', max_length=3)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='matrimony.MatrimonyProfile')),
            ],
            options={
                'db_table': 'matrimony_email_messages',
            },
        ),
    ]
