# Generated by Django 2.2.7 on 2021-06-21 08:52

from django.contrib.auth import get_user_model
from django.db import migrations


def set_matrimony_profile_id_as_username(apps, schema_editor):
    User = get_user_model()
    MatrimonyProfile = apps.get_model('matrimony', 'MatrimonyProfile')

    for mp in MatrimonyProfile.objects.all().values('profile_id', 'user'):
        if mp['user'] is None:
            continue
        user = User.objects.get(id=mp['user'])
        if user.is_staff:
            continue
        user.username = mp['profile_id']
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0010_auto_20210518_1342'),
    ]

    operations = [
        migrations.RunPython(set_matrimony_profile_id_as_username),
    ]
