# Generated by Django 2.2.7 on 2020-05-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0011_auto_20200510_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
