# Generated by Django 2.2.7 on 2020-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0011_auto_20200510_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='children',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Do you want Children'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='devotional_services',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='List your favorite devotional service'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='languages_read_write',
            field=models.ManyToManyField(related_name='languages_read_write', to='matrimony.Language', verbose_name='Languages known to read and write'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='medical_history',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mentor1',
            field=models.CharField(blank=True, help_text='Name, email and mobile number of your Spiritual Mentor/Counsellor 1', max_length=250, null=True, verbose_name='Reference 1'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mentor2',
            field=models.CharField(blank=True, help_text='Name, email and mobile number of your Spiritual Mentor/Counsellor 2', max_length=250, null=True, verbose_name='Reference 2'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='personality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Describe your personality'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='recreational_activities',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='List your favorite recreational activities'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religious Background of family'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kgs', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='languages_known',
            field=models.ManyToManyField(help_text='Languages you know', related_name='languages_known', to='matrimony.Language'),
        ),
    ]
