# Generated by Django 2.2.7 on 2020-05-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0012_auto_20200511_1513'),
        ('matrimony', '0012_auto_20200514_1412'),
    ]

    operations = [
    ]
