# Generated by Django 2.2.7 on 2020-05-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0014_auto_20200515_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='family_details',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='brothers',
            field=models.IntegerField(null=True, verbose_name='No. of Brothers'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='brothers_married',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='education_detail',
            field=models.CharField(max_length=100, null=True, verbose_name='Education in Detail'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='employed_in',
            field=models.CharField(choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('DEF', 'Defence'), ('NW', 'Not Working')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_location',
            field=models.CharField(choices=[('SAME', 'Same as my location'), ('DIFFERENT', 'Different Loca4ion')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_origin',
            field=models.CharField(help_text="Ancestral origin or father's birth place", max_length=50, null=True, verbose_name='Ancesteral/Family Origin'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_status',
            field=models.CharField(choices=[('LC', 'Lower Class'), ('MC', 'Upper Middle Class'), ('AF', 'Affluent')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_type',
            field=models.CharField(choices=[('JF', 'Joint Family'), ('NF', 'Nuclear Family'), ('OTH', 'Others')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_values',
            field=models.CharField(choices=[('ORTH', 'Orthodox'), ('TRAD', 'Traditional'), ('MOD', 'Moderate'), ('LIB', 'Liberal')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='father_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_occupation', to='matrimony.Occupation', verbose_name="Father's Occupation"),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='institution',
            field=models.CharField(help_text='Enter College/Institution Name', max_length=75, null=True, verbose_name='College/Institution'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mother_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_occupation', to='matrimony.Occupation', verbose_name="Mother's Occupation"),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='occupation_detail',
            field=models.CharField(max_length=100, null=True, verbose_name='Occupation in Detail'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='organization',
            field=models.CharField(help_text='Enter Organization Name', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='sisters',
            field=models.IntegerField(null=True, verbose_name='No. of Sisters'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='sisters_married',
            field=models.IntegerField(null=True),
        ),
    ]
