# Generated by Django 2.2.7 on 2020-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0015_auto_20200516_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='education_detail',
            new_name='education_details',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='occupation_detail',
            new_name='occupation_details',
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='personality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Describe yourself'),
        ),
    ]
