# Generated by Django 2.2.7 on 2020-05-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0016_auto_20200516_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['name'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='educationcategory',
            options={'verbose_name_plural': 'Education Categories'},
        ),
        migrations.AlterModelOptions(
            name='occupationcategory',
            options={'verbose_name_plural': 'Occupation Categories'},
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='body_type',
            field=models.CharField(choices=[('SLM', 'Slim'), ('AVG', 'Average'), ('ATH', 'Athelete'), ('HEA', 'Heavy')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='children',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Do you want Children'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(choices=[('FAI', 'Fair'), ('VFA', 'Very fair'), ('WHT', 'Wheatish'), ('WHB', 'Wheatish brown'), ('DAR', 'Dark')], help_text='Enter your complexion', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='devotional_services',
            field=models.CharField(max_length=250, null=True, verbose_name='List your favorite devotional service'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in cms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='medical_history',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mentor1',
            field=models.CharField(help_text='Name, email and mobile number of your Spiritual Mentor/Counsellor 1', max_length=250, null=True, verbose_name='Reference 1'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='personality',
            field=models.CharField(max_length=250, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='recreational_activities',
            field=models.CharField(max_length=250, null=True, verbose_name='List your favorite recreational activities'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kgs', max_digits=5, null=True),
        ),
    ]
