# Generated by Django 3.0.13 on 2022-08-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony', '0016_auto_20220827_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(blank=True, choices=[('USR', 'User'), ('STF', 'Staff'), ('SYS', 'Auto generated')], default='STF', max_length=3),
        ),
        migrations.AddField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='is_mutual',
            field=models.NullBooleanField(help_text='Is it a mutual match based on expectations?'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_visible',
            field=models.NullBooleanField(help_text='Is match visible to users?'),
        ),
        migrations.AddField(
            model_name='match',
            name='notified',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='sender_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('SUG', 'Suggested'), ('SNT', 'Sent'), ('TON', 'To notify'), ('NTF', 'Notified'), ('ACP', 'Accepted'), ('REJ', 'Rejected'), ('FOL', 'Follow up'), ('PRD', 'Parties discussing'), ('MRC', 'Marriage cancelled'), ('MRF', 'Marriage finalized'), ('MRD', 'Married')], default='', max_length=3),
        ),
    ]
