# Generated by Django 2.2.7 on 2020-05-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0017_auto_20200519_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='education_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Education in Detail'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_location',
            field=models.CharField(choices=[('SAME', 'Same as my location'), ('DIFFERENT', 'Different Location')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_status',
            field=models.CharField(choices=[('LC', 'Lower Class'), ('UC', 'Upper Class'), ('MC', 'Upper Middle Class'), ('AF', 'Affluent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='occupation_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation in Detail'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='subcaste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Subcaste'),
        ),
    ]
