# Generated by Django 3.0.13 on 2023-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0018_auto_20230102_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='response',
            field=models.CharField(blank=True, choices=[('', ''), ('ACP', 'Accepted'), ('REJ', 'Rejected')], default='', help_text='Combined response from both parties of the match', max_length=3),
        ),
    ]
