# Generated by Django 2.2.7 on 2020-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0018_auto_20200530_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
