# Generated by Django 2.2.7 on 2020-05-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0019_auto_20200531_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='children',
            new_name='want_children',
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='education_details',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Education in Detail'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='medical_history',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='occupation_details',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Occupation in Detail'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='personality',
            field=models.TextField(max_length=1500, null=True, verbose_name='Describe yourself'),
        ),
    ]
