# Generated by Django 3.0.13 on 2023-11-02 08:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0020_auto_20231102_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='marital_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UMR', 'Unmarried'), ('DIV', 'Divorced'), ('WID', 'Widowed'), ('WIR', 'Widower')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='marital_status',
            field=models.CharField(choices=[('UMR', 'Unmarried'), ('DIV', 'Divorced'), ('WID', 'Widowed'), ('WIR', 'Widower')], max_length=3, null=True),
        ),
    ]
