# Generated by Django 2.2.7 on 2020-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0020_auto_20200531_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='spiritual_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Spiritual name'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='spiritual_status',
            field=models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter spiritual status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Spiritual Status'),
        ),
    ]
