# Generated by Django 3.0.13 on 2023-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0020_auto_20231025_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
