# Generated by Django 3.0.13 on 2023-11-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0021_auto_20231102_0837'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('LC', 'Lower Class'), ('UC', 'Upper Class'), ('M', 'Middle Class'), ('MC', 'Upper Middle Class'), ('AF', 'Affluent')], max_length=2, null=True),
        ),
    ]
