# Generated by Django 2.2.7 on 2020-05-31 14:49

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0021_auto_20200531_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='expectations',
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_from', models.PositiveIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveIntegerField(blank=True, null=True)),
                ('height_from', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_to', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marital_status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UMR', 'Unmarried'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widowed')], max_length=3, null=True)),
                ('employed_in', multiselectfield.db.fields.MultiSelectField(choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('DEF', 'Defence'), ('NW', 'Not Working')], max_length=3, null=True)),
                ('annual_income_from', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_income_to', models.PositiveIntegerField(blank=True, null=True)),
                ('partner_description', models.TextField(blank=True, max_length=1500, null=True)),
                ('caste', models.ManyToManyField(blank=True, to='matrimony.Caste')),
                ('country', models.ManyToManyField(blank=True, to='matrimony.Country')),
                ('education', models.ManyToManyField(blank=True, to='matrimony.Education')),
                ('mother_tongue', models.ManyToManyField(blank=True, to='matrimony.Language')),
                ('occupation', models.ManyToManyField(blank=True, to='matrimony.Occupation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectantions', to='matrimony.MatrimonyProfile')),
                ('religion', models.ManyToManyField(blank=True, to='matrimony.Religion')),
                ('subcaste', models.ManyToManyField(blank=True, to='matrimony.Subcaste')),
            ],
            options={
                'db_table': 'marimony_expectations',
            },
        ),
    ]
