# Generated by Django 2.2.7 on 2020-05-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0022_auto_20200531_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectantions', to='matrimony.MatrimonyProfile', unique=True),
        ),
    ]
