# Generated by Django 3.0.13 on 2023-10-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0022_matrimonyprofile_actual_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='actual_dob',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Actual Date of birth'),
        ),
    ]
