# Generated by Django 3.0.13 on 2023-10-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0023_auto_20231025_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='no_of_children',
            field=models.CharField(blank=True, default='0', help_text='Specify If Have Children', max_length=10, verbose_name='No Of Children'),
        ),
    ]
