# Generated by Django 2.2.7 on 2020-05-31 15:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0023_auto_20200531_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='employed_in',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('DEF', 'Defence'), ('NW', 'Not Working')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expectantions', to='matrimony.MatrimonyProfile'),
        ),
    ]
