# Generated by Django 2.2.7 on 2020-06-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0024_auto_20200531_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthCountry', to='matrimony.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of Brothers'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers_married',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCountry', to='matrimony.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_location',
            field=models.CharField(blank=True, choices=[('SAME', 'Same as my location'), ('DIFFERENT', 'Different Location')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_origin',
            field=models.CharField(blank=True, help_text="Ancestral origin or father's birth place", max_length=50, null=True, verbose_name='Ancesteral/Family Origin'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('LC', 'Lower Class'), ('UC', 'Upper Class'), ('MC', 'Upper Middle Class'), ('AF', 'Affluent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_type',
            field=models.CharField(blank=True, choices=[('JF', 'Joint Family'), ('NF', 'Nuclear Family'), ('OTH', 'Others')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_values',
            field=models.CharField(blank=True, choices=[('ORTH', 'Orthodox'), ('TRAD', 'Traditional'), ('MOD', 'Moderate'), ('LIB', 'Liberal')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='father_occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_occupation', to='matrimony.Occupation', verbose_name="Father's Occupation"),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='languages_known',
            field=models.ManyToManyField(blank=True, help_text='Languages you know', related_name='languages_known', to='matrimony.Language'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='languages_read_write',
            field=models.ManyToManyField(blank=True, related_name='languages_read_write', to='matrimony.Language', verbose_name='Languages known to read and write'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mother_occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_occupation', to='matrimony.Occupation', verbose_name="Mother's Occupation"),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of Sisters'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters_married',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='want_children',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('Mb', 'May be')], max_length=2, null=True, verbose_name='Do you want Children'),
        ),
    ]
