# Generated by Django 2.2.7 on 2020-06-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0025_auto_20200601_1538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupation',
            unique_together={('name', 'category')},
        ),
    ]
