# Generated by Django 2.2.7 on 2020-06-08 05:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0026_auto_20200601_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectation',
            name='diff_diksha_guru',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Can spouse have different diksha guru?'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='age_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='From age'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='age_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='To age'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='From annual income'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='To annual income'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='employed_in',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('NW', 'Not Working')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='height_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='From height'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='height_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='To height'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='matrimony.MatrimonyProfile'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='employed_in',
            field=models.CharField(choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('NW', 'Not Working')], max_length=3, null=True),
        ),
    ]
