# Generated by Django 3.0.13 on 2023-12-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0027_auto_20231211_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Father name'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mother name'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Mother Phone number'),
        ),
    ]
