# Generated by Django 2.2.7 on 2020-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0027_auto_20200608_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='diff_diksha_guru',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True, verbose_name='Can the spouse have different a diksha-guru?'),
        ),
    ]
