# Generated by Django 2.2.7 on 2020-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0028_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('00', 'New'), ('01', 'Acknowledged'), ('02', 'Awaiting response'), ('03', 'Inactive'), ('04', 'Blocked'), ('10', 'Active'), ('11', 'Backlog'), ('12', 'In progress'), ('13', 'On hold'), ('20', 'Married (outside sources)'), ('30', 'Married')], default='00', max_length=2),
        ),
    ]
