# Generated by Django 2.2.7 on 2020-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0029_auto_20200609_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectation',
            name='color_of_eyes',
        ),
        migrations.RemoveField(
            model_name='expectation',
            name='hair_color',
        ),
        migrations.AddField(
            model_name='expectation',
            name='spiritual_status',
            field=models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter spiritual status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Spiritual Status'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='color_of_eyes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='hair_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='expectation',
            table='matrimony_expectations',
        ),
    ]
