# Generated by Django 2.2.7 on 2020-06-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0029_matrimonyprofile_status'),
        ('matrimony', '0031_auto_20200616_0622'),
    ]

    operations = [
    ]
