# Generated by Django 2.2.7 on 2020-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0033_auto_20200620_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
