# Generated by Django 2.2.7 on 2020-06-20 14:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0035_auto_20200620_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_from',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=10, null=True, verbose_name='From annual income'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_to',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=10, null=True, verbose_name='To annual income'),
        ),
    ]
