# Generated by Django 2.2.7 on 2020-06-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0036_auto_20200620_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='occupation',
            field=models.ForeignKey(blank=True, help_text='Doctor, Engineer, Entrepreneur etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Occupation'),
        ),
    ]
