# Generated by Django 2.2.7 on 2020-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0037_auto_20200620_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='family_origin',
            field=models.CharField(blank=True, help_text="Ancestral origin or father's birth place", max_length=50, null=True, verbose_name='Ancestral/Family Origin'),
        ),
    ]
