# Generated by Django 2.2.7 on 2020-06-26 14:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0037_auto_20200620_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='employed_in',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('NW', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='marital_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UMR', 'Unmarried'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widowed')], max_length=100, null=True),
        ),
    ]
