# Generated by Django 2.2.7 on 2020-07-03 04:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0038_auto_20200626_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=17, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'mentor',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='expectation',
            name='four_reg_principles',
        ),
        migrations.AddField(
            model_name='expectation',
            name='want_NRI',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('Mb', 'May be')], max_length=2, null=True, verbose_name='Do you want NRI'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='gotra',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='have_children',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='parents_devotees',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('OF', 'Only Father'), ('OM', 'Only Mother')], max_length=2, null=True, verbose_name='Are you parents devotees?'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='employed_in',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PSU', 'Government/PSU'), ('PVT', 'Private'), ('BUS', 'Business'), ('DEF', 'Defence'), ('SE', 'Self Employed'), ('NW', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='marital_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UMR', 'Unmarried'), ('DIV', 'Divorced'), ('WID', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='spiritual_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin'), ('NA', 'Not Applicable')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='marital_status',
            field=models.CharField(choices=[('UMR', 'Unmarried'), ('DIV', 'Divorced'), ('WID', 'Widowed')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mentor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor1', to='matrimony.Mentor'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mentor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor2', to='matrimony.Mentor'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='spiritual_status',
            field=models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin'), ('NA', 'Not Applicable')], help_text='Enter spiritual status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Spiritual Status'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
