# Generated by Django 2.2.7 on 2020-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0039_auto_20200702_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectation',
            name='four_reg_principles',
        ),
        migrations.AddField(
            model_name='expectation',
            name='want_NRI',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('Mb', 'May be')], max_length=2, null=True, verbose_name='Do you want NRI'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='parents_devotees',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('OF', 'Only Father'), ('OM', 'Only Mother')], max_length=2, null=True, verbose_name='Are you parents devotees?'),
        ),
    ]
