# Generated by Django 2.2.7 on 2020-07-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0039_auto_20200703_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gotra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gotra',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='want_NRI',
            new_name='want_nri',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='parents_devotees',
            new_name='are_parents_devotees',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='have_children',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='mentor1',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='mentor2',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='children_count',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mentor',
            field=models.ManyToManyField(to='matrimony.Mentor'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='gotra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Gotra'),
        ),
    ]
