# Generated by Django 2.2.7 on 2020-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0040_auto_20200703_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.ManyToManyField(to='matrimony.MatrimonyProfile'),
        ),
    ]
