# Generated by Django 2.2.7 on 2020-07-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0040_auto_20200702_1111'),
        ('matrimony', '0038_auto_20200626_1402'),
    ]

    operations = [
    ]
