# Generated by Django 2.2.7 on 2020-07-02 11:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0041_merge_20200702_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='marital_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UMR', 'Unmarried'), ('DIV', 'Divorced'), ('WID', 'Widowed')], max_length=100, null=True),
        ),
    ]
