# Generated by Django 2.2.7 on 2020-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0041_auto_20200704_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='profile',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mentors',
            field=models.ManyToManyField(to='matrimony.Mentor'),
        ),
    ]
