# Generated by Django 2.2.7 on 2020-07-11 06:28

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0042_auto_20200704_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('to_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('from_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
