# Generated by Django 2.2.7 on 2020-07-25 15:59

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0043_auto_20200725_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='birth_place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='birth_tz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
