# Generated by Django 2.2.7 on 2020-07-11 06:43

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0043_currencyexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=djmoney.models.fields.CurrencyField(default='XYZ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=djmoney.models.fields.CurrencyField(default='XYZ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
