# Generated by Django 2.2.7 on 2020-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0044_auto_20200711_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchangerate',
            options={'ordering': ['from_currency']},
        ),
        migrations.RenameField(
            model_name='currencyexchangerate',
            old_name='from_value',
            new_name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='to_value',
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.CharField(default='INR', max_length=3, null=True),
        ),
    ]
