# Generated by Django 2.2.7 on 2020-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0045_auto_20200718_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
