# Generated by Django 2.2.7 on 2020-07-26 11:24

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0045_auto_20200726_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='current_place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_city',
            field=models.CharField(blank=True, help_text='Enter current village/town/city', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCountry', to='matrimony.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State'),
        ),
    ]
