# Generated by Django 2.2.7 on 2020-07-26 11:44

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0046_auto_20200726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_place',
            field=places.fields.PlacesField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_place',
            field=places.fields.PlacesField(max_length=255, null=True),
        ),
    ]
