# Generated by Django 2.2.7 on 2020-07-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0047_auto_20200726_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='mentors',
        ),
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='matrimony.MatrimonyProfile'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
