# Generated by Django 2.2.7 on 2020-07-27 05:17

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0048_auto_20200726_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_from',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True, verbose_name='From annual income'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_from_in_base_currency',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True, verbose_name='From annual income (INR)'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_to',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True, verbose_name='To annual income'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='annual_income_to_in_base_currency',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True, verbose_name='To annual income (INR)'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='annual_income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='annual_income_in_base_currency',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True, verbose_name='Annual income in INR'),
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together={('name', 'profile')},
        ),
    ]
