# Generated by Django 2.2.7 on 2020-07-27 05:34

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0049_auto_20200727_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='annual_income',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='INR', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='are_parents_devotees',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('OF', 'Only Father'), ('OM', 'Only Mother')], max_length=2, null=True, verbose_name='Are your parents devotees?'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Caste'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='devotional_services',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='List your favorite devotional service'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='ethnic_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnic_origin', to='matrimony.Nationality'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='medical_history',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='personality',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='recreational_activities',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='List your favorite recreational activities'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Religion'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='tob',
            field=models.TimeField(blank=True, help_text='Enter time HH:MM:SS in 24hr format', null=True, verbose_name='Birth Time'),
        ),
    ]
