# Generated by Django 2.2.7 on 2020-07-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0050_auto_20200727_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='occupation',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='occupations',
            field=models.ManyToManyField(blank=True, help_text='Doctor, Engineer, Entrepreneur etc.', to='matrimony.Occupation'),
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='education',
            field=models.ManyToManyField(blank=True, help_text='HS, Graduate etc.', to='matrimony.Education'),
        ),
    ]
