# Generated by Django 2.2.7 on 2020-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0051_auto_20200727_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='want_children',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('Mb', 'May be')], max_length=2, null=True, verbose_name='Do you want Children'),
        ),
    ]
