# Generated by Django 2.2.7 on 2020-08-06 06:02

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0052_auto_20200727_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SLM', 'Slim'), ('AVG', 'Average'), ('ATH', 'Athelete'), ('HEA', 'Heavy')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAI', 'Fair'), ('VFA', 'Very fair'), ('WHT', 'Wheatish'), ('WHB', 'Wheatish brown'), ('DAR', 'Dark')], help_text='Enter your complexion', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kgs', max_digits=5, null=True),
        ),
    ]
