# Generated by Django 2.2.7 on 2020-08-24 07:57

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0052_auto_20200727_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='father_occupation',
            field=models.CharField(choices=[('EMP', 'Employed'), ('BUS', 'Business'), ('PRO', 'Professional'), ('RET', 'Retired'), ('NMP', 'Not Employed'), ('DEC', 'Deceased')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mother_occupation',
            field=models.CharField(choices=[('HMK', 'Home Maker'), ('EMP', 'Employed'), ('BUS', 'Business'), ('PRO', 'Professional'), ('RET', 'Retired'), ('NMP', 'Not Employed'), ('DEC', 'Deceased')], max_length=3, null=True),
        ),
    ]
