# Generated by Django 2.2.7 on 2020-08-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0054_auto_20200824_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='matches',
        ),
        migrations.CreateModel(
            name='MatrimonyProfileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches_suggested', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_accepted', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_rejected', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_accepted_by', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('matches_rejected_by', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matrimony.MatrimonyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
