# Generated by Django 2.2.7 on 2020-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0054_auto_20200824_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SLM', 'Slim'), ('AVG', 'Average'), ('ATH', 'Athelete'), ('HEA', 'Heavy')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAI', 'Fair'), ('VFA', 'Very fair'), ('WHT', 'Wheatish'), ('WHB', 'Wheatish brown'), ('DAR', 'Dark')], help_text='Enter your complexion', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kgs', max_digits=5, null=True),
        ),
    ]
