# Generated by Django 2.2.7 on 2020-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0055_auto_20200826_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category_text',
            field=models.CharField(blank=True, default='', editable=False, max_length=75),
        ),
        migrations.AddField(
            model_name='occupation',
            name='category_text',
            field=models.CharField(blank=True, default='', editable=False, max_length=75),
        ),
    ]
