# Generated by Django 2.2.7 on 2020-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0056_auto_20200826_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Brothers'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers_married',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='rounds_chanting',
            field=models.PositiveIntegerField(default=0, help_text='How many rounds are you chanting?', verbose_name='Rounds'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Sisters'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters_married',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
