# Generated by Django 2.2.7 on 2020-08-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0057_auto_20200826_1626'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matrimonyprofilestats',
            table='matrimony_profile_stats',
        ),
    ]
