# Generated by Django 2.2.7 on 2020-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0057_auto_20200826_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='min_rounds_chanting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum rounds of japa'),
        ),
    ]
