# Generated by Django 2.2.7 on 2020-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0058_auto_20200826_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='min_rounds_chanting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum rounds of japa'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SLM', 'Slim'), ('AVG', 'Average'), ('ATH', 'Athelete'), ('HEA', 'Heavy')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Brothers'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='brothers_married',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAI', 'Fair'), ('VFA', 'Very fair'), ('WHT', 'Wheatish'), ('WHB', 'Wheatish brown'), ('DAR', 'Dark')], help_text='Enter your complexion', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='father_status',
            field=models.CharField(blank=True, choices=[('EMP', 'Employed'), ('BUS', 'Business'), ('PRO', 'Professional'), ('RET', 'Retired'), ('NMP', 'Not Employed'), ('DEC', 'Deceased')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='mother_status',
            field=models.CharField(blank=True, choices=[('HMK', 'Home Maker'), ('EMP', 'Employed'), ('BUS', 'Business'), ('PRO', 'Professional'), ('RET', 'Retired'), ('NMP', 'Not Employed'), ('DEC', 'Deceased')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='rounds_chanting',
            field=models.PositiveIntegerField(default=0, help_text='How many rounds are you chanting?', verbose_name='Rounds'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No. of Sisters'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='sisters_married',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kgs', max_digits=5, null=True),
        ),
    ]
