# Generated by Django 2.2.7 on 2020-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0058_auto_20200826_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
