# Generated by Django 2.2.7 on 2020-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('matrimony', '0059_auto_20200829_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='matrimony_i_profile_a2f0c8_idx',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='photos',
            field=models.ManyToManyField(blank=True, through='matrimony.Photo', to='photologue.Photo'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['profile'], name='matrimony_p_profile_e94af6_idx'),
        ),
        migrations.AlterModelTable(
            name='photo',
            table='matrimony_photos',
        ),
    ]
