# Generated by Django 2.2.7 on 2020-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('matrimony', '0059_auto_20200827_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='images',
            field=models.ManyToManyField(blank=True, to='photologue.Photo'),
        ),
    ]
