# Generated by Django 2.2.7 on 2020-09-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0060_auto_20200829_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrimony.Nationality'),
        ),
    ]
