# Generated by Django 2.2.7 on 2020-09-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0061_auto_20200910_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='phone',
            field=models.CharField(max_length=17, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
