# Generated by Django 2.2.7 on 2020-09-20 15:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0065_auto_20200920_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='spiritual_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin'), ('NA', 'Not Applicable')], max_length=50, null=True),
        ),
    ]
