# Generated by Django 2.2.7 on 2020-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0066_auto_20200920_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='caste_other',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other caste'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='subcaste_other',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Other subcaste'),
        ),
        migrations.AlterField(
            model_name='caste',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
