# Generated by Django 2.2.7 on 2020-09-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0067_auto_20200920_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_city',
            field=models.CharField(blank=True, help_text='Birth village/town/city (auto populated from map)', max_length=200, null=True, verbose_name='City of birth'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthCountry', to='matrimony.Country', verbose_name='Country of birth'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='birth_state',
            field=models.CharField(blank=True, help_text='Auto populated from map', max_length=200, null=True, verbose_name='State of birth'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_city',
            field=models.CharField(blank=True, help_text='Current village/town/city (auto populated from map)', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='current_state',
            field=models.CharField(blank=True, help_text='Auto populated from map', max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
