# Generated by Django 2.2.7 on 2020-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0068_auto_20200921_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_person_name',
            field=models.CharField(default='', max_length=200, verbose_name='Contact person name'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='profile_created_by',
            field=models.CharField(choices=[('SE', 'Self'), ('PA', 'Parent'), ('SI', 'Sibling'), ('CO', 'Counselor'), ('FR', 'Friend')], default='SE', max_length=2),
        ),
    ]
