[tool.black]
line-length = 88
# skip-string-normalization = true
skip-numeric-underscore-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | locale
  | node_modules
  | compose
  | \.envs
  | .*migrations
)/
'''
