# Generated by Django 2.2.7 on 2020-09-18 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_matrimony_candidate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is matrimony candidate?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_matrimony_registration_complete',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is matrimony candidate?'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
    ]
