# Generated by Django 2.2.7 on 2022-07-22 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200919_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_updates', models.BooleanField(default=True, verbose_name='Product Updates')),
                ('announcements', models.BooleanField(default=True, verbose_name='Announcements')),
                ('matches_suggested', models.BooleanField(default=True, verbose_name='Matches Suggested')),
                ('matches_accepted', models.BooleanField(default=True, verbose_name='Matches Accepted')),
                ('matches_received', models.BooleanField(default=True, verbose_name='Matches Received')),
                ('matches_rejected', models.BooleanField(default=True, verbose_name='Matches Rejected')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
