# Generated by Django 2.2.7 on 2022-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usernotificationpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='announcements',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='matches_accepted',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='matches_received',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='matches_rejected',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='matches_suggested',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='product_updates',
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='email_announcements',
            field=models.BooleanField(default=True, verbose_name='Announcements'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='email_matrimony',
            field=models.BooleanField(default=True, verbose_name='Matches Suggested'),
        ),
    ]
