# Generated by Django 2.2.7 on 2019-12-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Language')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Language Code')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, unique=True, verbose_name='Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('rounds_chanting', models.PositiveIntegerField(default=0, help_text='How many rounds are you chanting?', verbose_name='Rounds')),
                ('s_status', models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter siksha status (e.g. Aspiring, Shelter etc.)', max_length=1, verbose_name='Siksha Status')),
                ('dob', models.DateField(help_text='Enter birth date as YYYY-MM-DD', verbose_name='Birth Date')),
                ('tob', models.TimeField(help_text='Enter time HH:MM:SS in 24hr format', verbose_name='Birth Time')),
                ('birth_city', models.CharField(help_text='Enter birth village/town/city', max_length=200, verbose_name='City')),
                ('birth_state', models.CharField(max_length=200, verbose_name='State')),
                ('birth_country', models.CharField(max_length=200, verbose_name='Country')),
                ('current_city', models.CharField(help_text='Enter current village/town/city', max_length=200, verbose_name='City')),
                ('current_state', models.CharField(max_length=200, verbose_name='State')),
                ('current_country', models.CharField(max_length=200, verbose_name='Country')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cms', max_digits=5)),
                ('annual_income', models.IntegerField(help_text='Enter income in a year')),
                ('marital_status', models.CharField(choices=[('SGL', 'Single'), ('ENG', 'Engaged'), ('MRD', 'Married'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widow')], help_text='Single, Divorced etc.', max_length=3)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, verbose_name='Phone number')),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Guru')),
                ('languages_known', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Language')),
                ('occupation', models.ForeignKey(help_text='Doctor, Engineer, Businessman etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Occupation')),
                ('qualification', models.ForeignKey(help_text='H.S., Graduate etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Qualification')),
            ],
        ),
    ]
