# Generated by Django 2.2.7 on 2019-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191227_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='languages_known',
            field=models.ManyToManyField(help_text='Add the language you know', to='profiles.Language'),
        ),
    ]
