# Generated by Django 2.2.7 on 2019-12-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191227_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthCountry', to='profiles.Country', verbose_name='Country'),
        ),
    ]
