# Generated by Django 2.2.7 on 2019-12-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191227_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['occupation']},
        ),
    ]
