# Generated by Django 2.2.7 on 2019-12-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191230_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255, unique=True, verbose_name='Degree')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualification',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.AddField(
            model_name='person',
            name='degree',
            field=models.ForeignKey(help_text='H.S., Graduate etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Degree'),
        ),
    ]
