# Generated by Django 2.2.7 on 2019-12-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20191230_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(help_text='Surgeon, Computer Application Engineer, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Occupation'),
        ),
    ]
