# Generated by Django 2.2.7 on 2019-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20191230_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='annual_income',
            field=models.PositiveIntegerField(help_text='Enter income in a year'),
        ),
    ]
