# Generated by Django 2.2.7 on 2019-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20191230_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('SGL', 'Single'), ('ENG', 'Engaged'), ('SEP', 'Separated'), ('DIV', 'Divorced'), ('WID', 'Widow')], help_text='Single, Divorced etc.', max_length=3),
        ),
    ]
