# Generated by Django 2.2.7 on 2019-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20191230_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='s_status',
            field=models.CharField(blank=True, choices=[('A', 'Aspiring'), ('S', 'Shelter'), ('D1', 'Harinam'), ('D2', 'Brahmin')], help_text='Enter siksha status (e.g. Aspiring, Shelter etc.)', max_length=2, verbose_name='Siksha Status'),
        ),
    ]
