# Generated by Django 2.2.7 on 2020-01-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_person_expectations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='MatrimonyProfile',
        ),
        migrations.AlterModelTable(
            name='degree',
            table='degree',
        ),
        migrations.AlterModelTable(
            name='guru',
            table='guru',
        ),
        migrations.AlterModelTable(
            name='matrimonyprofile',
            table='matrimony_profile',
        ),
        migrations.AlterModelTable(
            name='occupation',
            table='occupation',
        ),
    ]
